ARDUINO_DIR     = /usr/share/arduino
ARDMK_DIR       = /usr/share/arduino
#AVR_TOOLS_DIR  = /usr
#ARDUINO_LIBS   = Ethernet SPI
ARDUINO_LIBS   = Wire SPI Adafruit_BusIO Adafruit_GFX_Library Adafruit_SSD1306
BOARD_TAG       = uno
#BOARD_TAG       = yun
MONITOR_PORT    = /dev/ttyACM1
AVRDUDE         = /usr/share/arduino/hardware/tools/avrdude
AVRDUDE_CONF    = /usr/share/arduino/hardware/tools/avrdude.conf

include /usr/share/arduino/Arduino.mk
