ARDUINO_DIR     = /usr/share/arduino
ARDMK_DIR       = /usr/share/arduino
#AVR_TOOLS_DIR  = /usr
#ARDUINO_LIBS   = Ethernet SPI
BOARD_TAG       = uno
MONITOR_PORT    = /dev/ttyACM0
AVRDUDE         = /usr/share/arduino/hardware/tools/avrdude
AVRDUDE_CONF    = /usr/share/arduino/hardware/tools/avrdude.conf

include /usr/share/arduino/Arduino.mk
