#vim: noexpandtab: ts=8: softtabstop=8
#/*minimal Makefile*/
TARGET 	= testing_C
CC 	= gcc
            
$(TARGET):
	$(CC) minimal.c -o $(TARGET)

all:
	$(TARGET)

run: $(TARGET)
	./$(TARGET)

listfiles:
	ls -lAh
